### ISSUE TITLE
How does this Compare with ioredis

### ISSUE THREAD

**Issue by onkis** [apechimp/romis#8]
Hey @apechimp,
Hope all is well. How does this compare with ioredis https://github.com/luin/ioredis?

**Comment by apechimp** [comment]
Ahh, I haven't used redis in a little while, so ioredis is new to me.

This is a _very_ lightweight wrapper on top of node_redis with no changes to the API other than returning promises instead of accepting callbacks. I haven't used ioredis before, so I can't comment on it too much, but the API seems like an improvement and it appears that [ioredis and node_redis intend to consolidate](https://github.com/luin/ioredis#consolidation-its-time-for-celebration), so I'd imagine when that happens, this library won't need to exist anymore and I'll just maintain it for bug fixes.

Put another way, if ioredis existed when I made this library, I'd probably have used it instead of making this :smile_cat:
